### ISSUE TITLE
Possible to see scene acquisition dates in the Inspector?

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEEMMM#17]
Is it possible to have the Inspector tool tell users which scene a particular pixel has come from?  I can't see it anywhere
May be helpful in determining which scenes the best pixels are more within specified time ranges

![image](https://github.com/Blue-Ventures-Conservation/GEEMMM/assets/48567093/1eb882e0-459b-4af6-8f1a-3f9054f7e514)

**Comment by zibnix** [comment]
Thinking about this one, I don't believe there is a way to do this by default in GEE. We lose this sort of information when we create the composite using the `mosaic` or `qualityMosaic` functions on the `ImageCollection` in GEE.

We keep all the bands though, so we could encode the scene information into a numeric value and store that in a new band (or multiple new bands) for each pixel in the collection.. Something like a band each for day, month, year the pixel is from would be fairly easy and readable in the inspector.

**Comment by zibnix** [comment]
Ok, I've added these new bands to keep track of the scene date for each pixel in the final composites.
