### ISSUE TITLE
Mod2: Add dark green to colours

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEEMMM#18]
Is this a standard colour palette offered by GEE and can you add custom colours?
Dark green is the only one that comes to mind

![image](https://github.com/Blue-Ventures-Conservation/GEEMMM/assets/48567093/8581950c-92f3-4fae-8ba3-d37c80290302)

**Comment by zibnix** [comment]
According to GEE, we can use any web standard CSS color:
https://en.wikipedia.org/wiki/Web_colors#Extended_colors

I have added dark green!
