### ISSUE TITLE
LSIB coastline issue + exclusion areas

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEEMMM#4]
Are inland country borders being counted as coastline?
In our Casamance (Senegal) work we have an ROI coastline that goes inland along the Senegal-Guinea Bissau border (see graphic), resulting in considerable mangrove being highlighted well south of the ROI and into Guinea Bissau.  **A quick fix could be: limit the refined ROI (the buffered area) to the coarse ROI?**  A user isn't interested in anything outside their coarse ROI, but the sub-optimal method of buffering a not very good coastline dataset, in all directions (rather than just landward), is resulting in refined ROIs that can go well beyond the original coarse ROI limits.

Related to this, can Module 1's ROI buffer analysis account for given exclusion areas, i.e. any known mangrove that is inside the exclusion areas are _excluded_ from the known mangrove totals and bar chart?

![image](https://github.com/Blue-Ventures-Conservation/GEEMMM/assets/48567093/bec264f3-61f1-472b-bc19-a64c1c0040a3)

**Comment by zibnix** [comment]
Yes, unfortunately the GEM doesn't know if a line segment is on the coast or if it extends inland. The other coastline dataset you recommended does seem to improve this, at least in Casamance. It has fewer inland line segments since it doesn't follow borders, but it does have some odd inland sections as well so it's probably worth trying to adjust this either way.

**Comment by zibnix** [comment]
Ok, for this one I have adjusted the buffer code to not extend the buffer outside the original coarse ROI, as you suggested.

I have also updated the buffer imagery and buffer charts to take the `exclusion_geometries` into account and block those areas form the imagery on the map as well as from the data used in the chart. I believe this to now be fixed at the latest URL in the README.
