### ISSUE TITLE
Dynamics across classes

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEEMMM#6]
An important request from Awa:

In Module 3 can a table be presented (and downloadable) that shows conversion metrics from each class to each of the _other_ classes? This is particularly important for the mangrove classes, e.g. how much CCM has become OCM1, and vice versa?

Going further, could we allow the user to combine classes, so in a typical 9-class structure with multiple mangrove classes, could we allow the user to select all of the mangrove classes, to get total mangrove dynamics?

**Comment by zibnix** [comment]
This is completed and you should see much more information in the dynamics, as well as graphs for conversions between classes that can be downloaded.
