### ISSUE TITLE
Final mask isn't clipped to ROI like other masks

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEEMMM#8]
Can see final mask in semi-transparent in the background is the full area, whilst other masks are clipped to ROI.  More an optimisation to reduce file sizes than an issue (I think!)

![image](https://github.com/Blue-Ventures-Conservation/GEEMMM/assets/48567093/db07c094-d941-406e-851d-6a39f5607bc8)

**Comment by zibnix** [comment]
Updated!
